import type { DemoItem } from './p2-dashboard.type'

export const DEMOS: DemoItem[] = [
    {
        id: 'redux',
        title: 'Redux (Classic)',
        description: 'Counter with createStore, dispatch & subscribe',
        emoji: '🔄',
        color: '#764ABC',
        route: '/practical-2/redux',
    },
    {
        id: 'redux-toolkit',
        title: 'Redux Toolkit',
        description: 'Counter with createSlice, configureStore & useSelector',
        emoji: '🛠️',
        color: '#764ABC',
        route: '/practical-2/redux-toolkit',
    },
    {
        id: 'zustand',
        title: 'Zustand',
        description: 'Lightweight state management with zustand stores',
        emoji: '🐻',
        color: '#FF6B35',
        route: '/practical-2/zustand',
    },
    {
        id: 'mobx',
        title: 'MobX',
        description: 'Observable state with makeAutoObservable & reactions',
        emoji: '⚛️',
        color: '#FF7043',
        route: '/practical-2/mobx',
    },
    {
        id: 'context',
        title: 'Context API',
        description: 'Global state with React Context + useReducer',
        emoji: '🌐',
        color: '#00BCD4',
        route: '/practical-2/context',
    },
    {
        id: 'react-query',
        title: 'React Query',
        description: 'Fetch & cache server data with useQuery',
        emoji: '🔍',
        color: '#FF4154',
        route: '/practical-2/react-query',
    },
    {
        id: 'crud-api',
        title: 'CRUD API',
        description: 'Create, Read, Update, Delete via Axios',
        emoji: '📡',
        color: '#22C55E',
        route: '/practical-2/crud-api',
    },
    {
        id: 'graphql',
        title: 'GraphQL',
        description: 'Query a public GraphQL API with fetch()',
        emoji: '◈',
        color: '#E535AB',
        route: '/practical-2/graphql',
    },
    {
        id: 'redux-api',
        title: 'Redux + API',
        description: 'Async API calls using createAsyncThunk',
        emoji: '🚀',
        color: '#6C63FF',
        route: '/practical-2/redux-api',
    },
]
